### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by mathewpeterson** [josephdpurcell/code-climate-and-drupal#1]
I'm totally not cyber stalking you.

**Comment by josephdpurcell** [comment]
You would.

The code is in a encrypted and null-byte encoded format in /dev/null. I'll publish a copy of it soon.

**Comment by josephdpurcell** [comment]
I added some How-To's: https://github.com/josephdpurcell/code-climate-and-drupal#how-tos

They include links to gists that have teh codez.
