### ISSUE TITLE
Is the .phpmd.xml acceptable for Drupal?

### ISSUE THREAD

**Issue by josephdpurcell** [josephdpurcell/code-climate-and-drupal#2]
I've created a PHPMD configuration [here](https://github.com/josephdpurcell/code-climate-and-drupal/blob/gh-pages/.phpmd.xml) that modifies the out of the box config for PHPMD.

The reason for using PHPMD checks with Drupal is that it has checks for things like unused variables or access to globals or var_dumps which should be avoided, but are not part of Drupal's coder.

The question, however, is are the checks acceptable? This issue is for commentary.
# Participate in the discussion:
1. Read the checks that are used https://github.com/josephdpurcell/code-climate-and-drupal/blob/gh-pages/.phpmd.xml
2. Comment below a :+1: if it's good as is, else suggest an edit or state a question.

**Comment by alexfinnarn** [comment]
I'm trying to determine how relevant this repo still is in 09/2020. Surely this issue can be closed? I see `.phpmd.xml` code in this repo that I'll assume is acceptable.

**Comment by josephdpurcell** [comment]
The repo is primarily for the presentations I've done regarding static analysis and Drupal. Additionally, it includes some how-to setup for Code Climate.

I agree this issue should be closed, if nobody has commented in opposition to the phpmd file in 4 years I think the intent of this issue served its purpose. People can still interact with this project and voice their opinion about what a good phpmd file is by opening a new issue.

I personally use the phpmd file in this project. It is a better configuration for Drupal that using an unconfigured PHPMD which will throw lots of issues that are opinion-based and conflict with Drupal's opinions. This PHPMD file in this repo lets Drupal's opinion take priority.

Sorry for not replying sooner! I hope you find this project helpful.
