### ISSUE TITLE
Drupal 9 support

### ISSUE THREAD

**Issue by MPParsley** [josephdpurcell/code-climate-and-drupal#3]
Does this project require any specific changes for Drupal 9?

**Comment by josephdpurcell** [comment]
@MPParsley Sorry for a delayed reply!

Looking at the How To's here: https://github.com/josephdpurcell/code-climate-and-drupal/blob/gh-pages/docs/how-tos.md

From a PHP code perspective, there isn't a lot different in 8 vs 9 that I'm aware of as it relates to PHPMD and PHPCS. That is to say, the static analysis checks that applied to Drupal 8 should apply nicely to Drupal 9.

That said, there is a new mostly-static analysis tool called drupal-check, see it here: https://github.com/mglaman/drupal-check. This tool will help you analyze your project's compatibility with Drupal 9. If you're a contrib project maintainer, this tool might already be available to you on drupal.org? But, if you're building your own website project, this tool can be downloaded and used either locally or in a CI process.

Here is a blog post with more information: http://hojtsy.hu/blog/2019-apr-29/estimate-your-sites-drupal-9-compatibility-easily-upgrade-status

So, does this project require changes for Drupal 9? As best as I can tell, no, but it would be great to see a static analysis engine for drupal-check added to Code Climate. If that is of interest, you can read the Code Climate engine specification and see how to implement one: https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md
